name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube-scan:
    name: SonarQube scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

 #     - name: SonarQube Quality Gate
 #       uses: sonarsource/sonarqube-quality-gate-action@v1
 #       timeout-minutes: 5
 #       env:
 #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  npm-setup-scan:
    name: npm setup and scan
    runs-on: ubuntu-latest
    needs: sonarqube-scan
    steps:
      - name: checkout
        uses:  actions/checkout@v4

      - name: set up node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '25'

      - name: Install express
        run: npm install express

      - name: Run tests
        run: npm test # Run the project's tests 

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
        #  severity: 'HIGH,CRITICAL'
       #   exit-code: '1' # to make the flow fail in case of high or citical vulnerabilities

  docker-build-scan-push:
    name: docker build and trivy scan
    runs-on: ubuntu-latest
    needs: npm-setup-scan
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: thumama/nodeapp:${{ github.sha }}
          push: false
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: thumama/nodeapp:${{ github.sha }}
          format: table
      #    exit-code: 1
      #    severity: CRITICAL,HIGH

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: thumama/nodeapp:${{ github.sha }}
          push: true

    


  